/** @see https://mariadb.com/kb/en/connection/#capabilities */
export const Capabilities = {
  // Capabilities #1.
  CLIENT_MYSQL: 1n << 0n,
  FOUND_ROWS: 1n << 1n,
  CONNECT_WITH_DB: 1n << 3n,
  COMPRESS: 1n << 5n,
  LOCAL_FILES: 1n << 7n,
  CLIENT_PROTOCOL_41: 1n << 9n,
  CLIENT_INTERACTIVE: 1n << 10n,
  SSL: 1n << 11n,
  TRANSACTIONS: 1n << 13n,
  SECURE_CONNECTION: 1n << 15n,
  MULTI_STATEMENTS: 1n << 16n,

  // Capabilities #2.
  MULTI_RESULTS: 1n << 17n,
  PS_MULTI_RESULTS: 1n << 18n,
  PLUGIN_AUTH: 1n << 19n,
  CONNECT_ATTRS: 1n << 20n,
  PLUGIN_AUTH_LENENC_CLIENT_DATA: 1n << 21n,
  CLIENT_CAN_HANDLE_EXPIRED_PASSWORDS: 1n << 22n,
  CLIENT_SESSION_TRACK: 1n << 23n,
  CLIENT_DEPRECATE_EOF: 1n << 24n,
  CLIENT_ZSTD_COMPRESSION_ALGORITHM: 1n << 26n,
  CLIENT_CAPABILITY_EXTENSION: 1n << 29n,
  CLIENT_SSL_VERIFY_SERVER_CERT: 1n << 30n,
  CLIENT_REMEMBER_OPTIONS: 1n << 31n,

  // Capabilities #3.
  MARIADB_CLIENT_PROGRESS: 1n << 32n,
  MARIADB_CLIENT_RESERVED_1: 1n << 33n,
  MARIADB_CLIENT_STMT_BULK_OPERATIONS: 1n << 34n,
  MARIADB_CLIENT_EXTENDED_METADATA: 1n << 35n,
  MARIADB_CLIENT_CACHE_METADATA: 1n << 36n,
};

/** @see https://dev.mysql.com/doc/dev/mysql-server/latest/mysql__com_8h.html#a1d854e841086925be1883e4d7b4e8cad */
export const ServerStatus = {
  SERVER_STATUS_IN_TRANS: 1,
  SERVER_STATUS_AUTOCOMMIT: 2,
  SERVER_MORE_RESULTS_EXISTS: 8,
  SERVER_QUERY_NO_GOOD_INDEX_USED: 16,
  SERVER_QUERY_NO_INDEX_USED: 32,
  SERVER_STATUS_CURSOR_EXISTS: 64,
  SERVER_STATUS_LAST_ROW_SENT: 128,
  SERVER_STATUS_DB_DROPPED: 256,
  SERVER_STATUS_NO_BACKSLASH_ESCAPES: 512,
  SERVER_STATUS_METADATA_CHANGED: 1024,
  SERVER_QUERY_WAS_SLOW: 2048,
  SERVER_PS_OUT_PARAMS: 4096,
  SERVER_STATUS_IN_TRANS_READONLY: 8192,
  SERVER_SESSION_STATE_CHANGED: 1 << 14,
};
