name: Build
on: push

jobs:
  quality:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nodes:
          - 20
          - 22
          - latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodes }}
      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - run: pnpm install --frozen-lockfile
      - run: pnpm code:analysis

  prettier:
    needs: quality
    if: ${{ always() && contains(needs.quality.result, 'failure') }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nodes:
          - 20
          - 22
          - latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodes }}
      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - run: pnpm install --frozen-lockfile
      - run: pnpm prettier

  eslint:
    needs: quality
    if: ${{ always() && contains(needs.quality.result, 'failure') }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nodes:
          - 20
          - 22
          - latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodes }}
      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - run: pnpm install --frozen-lockfile
      - run: pnpm eslint

  tsc:
    needs: quality
    if: ${{ always() && contains(needs.quality.result, 'failure') }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nodes:
          - 20
          - 22
          - latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodes }}
      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - run: pnpm install --frozen-lockfile
      - run: pnpm tsc

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nodes:
          - 20
          - 22
          - latest
        databases:
          - mariadb:10.11
          - quay.io/mariadb-foundation/mariadb-devel:11.4
          - quay.io/mariadb-foundation/mariadb-devel:verylatest

    services:
      mariadb:
        image: ${{ matrix.databases }}
        ports:
          - 3306:3306
        env:
          MARIADB_USER: user
          MARIADB_ROOT_PASSWORD: password
          MARIADB_PASSWORD: password
          MARIADB_DATABASE: mariadb-alt
        options: >-
          --health-cmd="mariadb-admin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        volumes:
          - ${{ github.workspace }}/build:/etc/mysql/conf.d

    steps:
      - uses: actions/checkout@v4

      - name: Copy MariaDB configurations
        run: sudo cp ${{ github.workspace }}/build/my.cnf /etc/mysql/conf.d/my.cnf

      - name: Restart MariaDB
        run: docker restart $(docker ps -q)

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodes }}

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - run: pnpm install --frozen-lockfile

      - run: pnpm test
        env:
          TESTING_DATABASE: mariadb-alt
          TESTING_USER: user
          TESTING_PASSWORD: password
