name: Build
on: push

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      - run: npm run code:analysis

  prettier:
    needs: quality
    if: ${{ always() && contains(needs.quality.result, 'failure') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      - run: npm run prettier

  eslint:
    needs: quality
    if: ${{ always() && contains(needs.quality.result, 'failure') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      - run: npm run eslint

  tsc:
    needs: quality
    if: ${{ always() && contains(needs.quality.result, 'failure') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      - run: npm run tsc

  test:
    needs: quality
    runs-on: ubuntu-latest

    strategy:
      matrix:
        databases:
          - mariadb:10.11
          - mariadb:11.0-rc
          - quay.io/mariadb-foundation/mariadb-devel:11.1

    services:
      mariadb:
        image: ${{ matrix.databases }}
        ports:
          - 3306:3306
        env:
          MARIADB_USER: user
          MARIADB_ROOT_PASSWORD: password
          MARIADB_PASSWORD: password
          MARIADB_DATABASE: mariadb-alt
        options: >-
          --health-cmd="mariadb-admin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        volumes:
          - ${{ github.workspace }}/.github/build:/etc/mysql/conf.d

    steps:
      - uses: actions/checkout@v3

      - name: Copy MariaDB configurations
        run: sudo cp ${{ github.workspace }}/.github/build/custom.cnf /etc/mysql/conf.d/custom.cnf

      - name: Restart MariaDB
        run: docker restart $(docker ps -q)

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - run: npm run test:ci
        env:
          TESTING_DATABASE: mariadb-alt
          TESTING_USER: user
          TESTING_PASSWORD: password

      - run: npm run test:build:ci
        env:
          TESTING_DATABASE: mariadb-alt
          TESTING_USER: user
          TESTING_PASSWORD: password
